{
    'name': 'Library',
    'version': '1.0',
    'summary': 'Library App',
    'author': 'Syed Owais Noor',
    'website': 'https://bytesnode.com/',
    'license': 'LGPL-3',
    'category': 'BytesNode/Library',
    'depends': [
        'mail',
    ],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'data/server_action.xml',
        'data/schedule_action.xml',
        'views/search.xml',
        'views/form.xml',
        'views/tree.xml',
        'views/action.xml',
        'views/menu.xml',
    ],
    'auto_install': False,
    'application': True,
}